#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_Forms3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Zoo_Management")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LinQ_To_Forms3.Properties.Settings.Default.Zoo_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Animal_Type;
		
		private string _Animal_Name;
		
		private System.Nullable<int> _Animal_Count;
		
		private string _Animal_Diet;
		
		private System.Nullable<int> _Animal_SleepTime;
		
		private System.Nullable<int> _Animal_WakingHours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAnimal_TypeChanging(string value);
    partial void OnAnimal_TypeChanged();
    partial void OnAnimal_NameChanging(string value);
    partial void OnAnimal_NameChanged();
    partial void OnAnimal_CountChanging(System.Nullable<int> value);
    partial void OnAnimal_CountChanged();
    partial void OnAnimal_DietChanging(string value);
    partial void OnAnimal_DietChanged();
    partial void OnAnimal_SleepTimeChanging(System.Nullable<int> value);
    partial void OnAnimal_SleepTimeChanged();
    partial void OnAnimal_WakingHoursChanging(System.Nullable<int> value);
    partial void OnAnimal_WakingHoursChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_Type", DbType="NVarChar(MAX)")]
		public string Animal_Type
		{
			get
			{
				return this._Animal_Type;
			}
			set
			{
				if ((this._Animal_Type != value))
				{
					this.OnAnimal_TypeChanging(value);
					this.SendPropertyChanging();
					this._Animal_Type = value;
					this.SendPropertyChanged("Animal_Type");
					this.OnAnimal_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_Name", DbType="NVarChar(50)")]
		public string Animal_Name
		{
			get
			{
				return this._Animal_Name;
			}
			set
			{
				if ((this._Animal_Name != value))
				{
					this.OnAnimal_NameChanging(value);
					this.SendPropertyChanging();
					this._Animal_Name = value;
					this.SendPropertyChanged("Animal_Name");
					this.OnAnimal_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_Count", DbType="Int")]
		public System.Nullable<int> Animal_Count
		{
			get
			{
				return this._Animal_Count;
			}
			set
			{
				if ((this._Animal_Count != value))
				{
					this.OnAnimal_CountChanging(value);
					this.SendPropertyChanging();
					this._Animal_Count = value;
					this.SendPropertyChanged("Animal_Count");
					this.OnAnimal_CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_Diet", DbType="NVarChar(MAX)")]
		public string Animal_Diet
		{
			get
			{
				return this._Animal_Diet;
			}
			set
			{
				if ((this._Animal_Diet != value))
				{
					this.OnAnimal_DietChanging(value);
					this.SendPropertyChanging();
					this._Animal_Diet = value;
					this.SendPropertyChanged("Animal_Diet");
					this.OnAnimal_DietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_SleepTime", DbType="Int")]
		public System.Nullable<int> Animal_SleepTime
		{
			get
			{
				return this._Animal_SleepTime;
			}
			set
			{
				if ((this._Animal_SleepTime != value))
				{
					this.OnAnimal_SleepTimeChanging(value);
					this.SendPropertyChanging();
					this._Animal_SleepTime = value;
					this.SendPropertyChanged("Animal_SleepTime");
					this.OnAnimal_SleepTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_WakingHours", DbType="Int")]
		public System.Nullable<int> Animal_WakingHours
		{
			get
			{
				return this._Animal_WakingHours;
			}
			set
			{
				if ((this._Animal_WakingHours != value))
				{
					this.OnAnimal_WakingHoursChanging(value);
					this.SendPropertyChanging();
					this._Animal_WakingHours = value;
					this.SendPropertyChanged("Animal_WakingHours");
					this.OnAnimal_WakingHoursChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
